[package]
name = "cadd_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
convert_case = "0.10.0"
fs-err = "3.2.0"
itertools = "0.14.0"
prettyplease = "0.2.37"
proc-macro2 = { version = "1.0.103", features = ["span-locations"] }
quote = "1.0.42"
syn = { version = "2.0.111", features = ["parsing", "full", "extra-traits"] }
